### ISSUE TITLE
The patch for ukui-control-center needs to be updated

### ISSUE THREAD

**Issue by brsvh** [jenningsloy318/ukui-rpm-packaging#3]
`plugins/network/netconnect/netconnect.pro` and `plugins/devices/mousecontrol/mousecontrol.pro` has been modified.

**Comment by jenningsloy318** [comment]
Actually, I am still waiting for the official code updates regarding the build env that build env can get the libdir from system directly not hardcore,. This fix will be merged in next week

**Comment by brsvh** [comment]
Yes, adding the `QT_INSTALL_LIBS` constraint to all UKUI QMake-based projects is in progress.

**Comment by jenningsloy318** [comment]
emm, if the the transition is complemted, please file a nonitfication, I will update this repo accordingly.

**Comment by jenningsloy318** [comment]
Now no need this patch now

**Comment by brsvh** [comment]
yep, all such patches should be processed upstream.
